gstcefsrc.cc

This seems to help when running headless https://bitbucket.org/chromiumembedded/cef/issues/1368
Tested and it worked fine with it

Add enable-begin-frame-scheduling flag

---

gstcefsrc.cc

I'm not 100% sure when `gst_cef_src_init()` runs, is `state_lock` guaranteed to be initialized by the time I try to use it?

Allow loading a new url in the PLAYING state

---

.gitignore
gstcefsrc.cc
gstcefsrc.h

With GPU 60 fps
Without GPU only 6-7 fps
I'm still very surprised that this works. Was under impression that GPU in osr mode works only under windows
Tested with this site https://threejs.org/examples/#webgl_points_dynamic
p.s. first c code I write in years

Add a gpu support property

---

gstcefdemux.cc
gstcefsrc.cc

From what I know big-endian is rare format. When I was writing custom recorder for cef my output was in F32LE

Use F32LE format for audio

---

gstcefaudiometa.cc

Newer GCC complains with:
```
error: argument 2 of ‘__atomic_load’ must not be a pointer to a ‘volatile’ type
```

cefaudiometa: Remove incorrect use of volatile

---

gstcefaudiometa.cc
gstcefsrc.cc
gstcefsrc.h

Enables remote debugging for chromium

Add params to set chromium-debug-port

---

CMakeLists.txt
gstcefsrc.cc

Related to talks on #28 and #30
Removes `target_compile_definitions` for `gstcefsubprocess` and `locales` paths in favor of inferring path based on plugin location.

use plugin location to find gstcefsubprocess bin

---

CMakeLists.txt

Smoke-testing of a release build validated with:
gst-launch-1.0 cefsrc url="chrome://version" ! videoconvert ! queue ! gtksink

Update to CEF 103

---

gstcefsrc.cc
gstcefsrc.h

```
commit cf29643a3a59a2374514c47dca1d431505ca5f1e (HEAD -> additional-props)
Author: Philippe Normand <philn@igalia.com>
Date:   Wed Aug 3 12:17:48 2022 +0100
cefsrc: Add js-flags property
That can allow for instance to disable Wasm support.
commit d16f6c0f3efe40888698a8af2837892b30866005
Author: Philippe Normand <philn@igalia.com>
Date:   Wed Aug 3 12:05:48 2022 +0100
cefsrc: Add sandbox property
This property allows to enable or disable the Chromium sandbox. By default the
sandbox is enabled.
```

Additional properties

---

README.md
gstcefbin.cc

The URIs this element receives are not compliant with RFC 3986 because they have
2 protocol schemes (web://http://...). So we can't use the GstURI parser in
cefbin, we pass the unparsed URI stripped of the web:// or cef:// prefix to
cefsrc.
V2:
These URIs are RFC 3986 compliant, so allowing for clean removal of the web+
prefix before passing the URI to cefsrc.

cefbin: Change protocol handler to web+...://

---

gstcefsrc.cc
gstcefsrc.h

Allows users to define the log_severity setting in cef to `verbose / debug | info | warning | error | fatal | disable[default]` (corresponding to `cef_log_severity_t` options [here](https://magpcss.org/ceforum/apidocs3/projects/(default)/cef_types.h.html)).

cefsrc: Enable definition of cef log severity

---

CMakeLists.txt
README.md
cmake/DownloadCEF.cmake

if not provided with `-DCEF_VERSION=...` fallback to hardcoded version number.

cmake: Allow user-supplied CEF_VERSION override

---

gstcefsrc.cc

If an override is supplied with the GST_CEF_SUBPROCESS_PATH environment variable, we set CEF_SUBPROCESS_PATH to the real subprocess path and spawn the supplied override program instead. It is then free of configuring the subprocess for cgroups, for instance.

cefsrc: Allow custom CEF subprocess wrappers

---

gstcefsrc.cc
gstcefsrc.h

When recording same website multiple times it helps to have most resources cached :) 
Now looking at `CefSettings` I wish we could just pass json and fill it up. Could solve all similar PRs down the line.

cefsrc: Add cef_cache_location property

---

.github/workflows/pr-test.yml

Otherwise the Ubuntu 22.04 workflow fails with this error:
The following packages have unmet dependencies:
libunwind-14-dev : Breaks: libunwind-dev but 1.3.2-2build2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

CI: Install libunwind

---

CMakeLists.txt

Reverts centricular/gstcefsrc#67 due to the issue #68

Revert "fix builds on macos arm64 and pay attention to USE_SANDBOX flag"

---

gstcefbin.cc
gstcefdemux.cc
gstcefdemux.h
gstcefsrc.cc

Also add an audio meta to buffers, for good measure, and set discont flag when needed. This should help with A/V sync issues and audio cracks reported in #59.

cefsrc: Apply running time on audio buffers

---

gstcefdemux.cc

It looks like issue #73 was never addressed. This PR has the suggested fix.

Fix bad audio metadata (issues #73)

---

gstcefsrc.cc

Hi,
This addresses the issue in https://github.com/centricular/gstcefsrc/pull/83#issuecomment-2208943286 where CEF would deadlock on launch on macOS. I traced it to an incorrect assumption in my code, that GStreamer would always run in a separate thread; in the supplied app, GStreamer is handled from the Cocoa event loop.
While this was already addressed for the CEF startup itself, it didn't account for GStreamer's code flow before CEF initialization (GstElement's start handler runs before the call to `run_cef`) and on shutdown (there was no check for main thread, so the deadlock would've occurred on the call to `dispatch_async_f`).
Let me know if this is OK; I tested it locally with `gst-launch-1.0` and observed no issues.
cc @reinismu , can you check with your Nix recipe?

Fix deadlock on macOS when running GStreamer in the main thread

---

README.md
gstcefsrc.cc
gstcefsrc.h
gstcefsubprocess.cc
html/ready_test.html

Based on [this sample](https://bitbucket.org/chromiumembedded/cef-project/src/master/examples/message_router), this adds a way to signal in javascript (from the webpage) a couple of things:
- "ready" - page is ready for rendering, so enable cefsrc to go to a PAUSED/PLAYING state
- "eos" - page doesn't have any more content, so push an EOS event onto cefsrc
This is useful for pages that have non-trivial load times and may run out of content (webgl pages, pages with videos, etc).
There is a sample in the html/ directory that shows how to send the signals, e.g.:
```
window.gstSendMsg({
request: "ready",
onSuccess: function(response) { ... }
},
onFailure: function(error_code, error_message) { ... }
});
}
```
To test, run a webserver in the html directory, say:
```
python -m http.server 9000 …
```

Add javascript signalling

---

gstcefsrc.cc

Calling CefInitialize multiple times during a process lifetime is not supported:
* https://magpcss.org/ceforum/viewtopic.php?f=6&t=16430
* https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=466
* https://stackoverflow.com/questions/73172139/cef-can-only-be-initialized-once-per-process-this-is-a-limitation-of-the-underl
Prior to #83 we used to have a ShutdownEnforcer class, but as it was causing issues on OSX we will simply no longer shut down CEF at all.
We can revisit if needed, but this is preferable to crashing.
See https://github.com/centricular/gstcefsrc/pull/88#issuecomment-2388711778 and below

cefsrc: fix CefInitialize crashing the second time

---

README.md
gstcefsrc.cc

See https://github.com/centricular/gstcefsrc/pull/90#issuecomment-2393937044

properties: Move gpu and chrome_extra_flags to env vars

---

CMakeLists.txt
gstcefsrc.cc
gstcefsubprocess.cc

Hi all,
This PR fixes two issues I was made aware of today:
- the macOS sandbox logic was being mistakenly built on Linux
- the event loop handler was renamed in 1931ae13940c5cb82ee3a07d5fed914ecf9b92c6, but that was not carried over to the state change handler for macOS

Fix macOS and Linux build

---

CMakeLists.txt

Otherwise the plugin will fail to load

CMakeLists: Don't put target .so files in subdirectory
